### ISSUE TITLE
AYBE: Are you planning on merging these pull requests or what???

### ISSUE THREAD

**Issue by dirtygooback** [aybe/Windows-API-Code-Pack-1.1#25]
WTF AYBE??

**Comment by BasPaap** [comment]
Is this even still maintained? There are a lot of good fixes in these pull requests.

**Comment by aybe** [comment]
Hey, sorry about the really late answering but I had notifications turned off :)

I'd be more than happy on merging those PRs but the thing is
 - they should be checked
 - introducing changes for actual uses needs a *What's fixed ?* page
 - A/B testing cases should be added to the TestApp in the repo to easily check/pinpoint/fix

I just don't have time for this ...

Therefore I'd rather leave things as they are, dumping loads without any sort of notifications is just silly IMO

*unless*

anyone willing to do all of the above, I'll make it a collaborator on the repo.

Thanks for your understanding

**Comment by KAW24** [comment]
I think it's fair enough to require test cases being added although unit tests will be even better if the issue does not require a UI. I also agree that this is the responsibility of the submitter of the PR, but I think there needs to be clearer guidance, e.g. should test cases be added to the existing TestApp or have their own app? I'm prepared to perform reviews of some of the PRs if that helps but as it stands you have a repo (and NuGet package), which is broken on x64. Leaving things as they are also seems silly IMO.

**Comment by santiagoIT** [comment]
@aybe we just ran into a problem with the 64-bit build of our product. An exception was thrown almost everytime the TaskDialog was invoked. In 32-bit this never happenes.
It took us a while to figure out what the problem was. Using a dissembler we discovered that there is a bug in **NativeTaskDialog.AllocateAndMarshalButtons**.  What surprised me however is that a fix had already been submitted almost a year ago. It makes a lot of sense to request tests, etc. before accepting pull request. However this [fix ](https://github.com/aybe/Windows-API-Code-Pack-1.1/pull/20) is really straightforward. With the current code, TaskDialogs with custom buttons simply cannot be used reliably in 64-bit builds. Applying the fix solves the problem.
Thanks for all your work!

**Comment by BasPaap** [comment]
Alright, I don't have a lot of time either but it's too painful to see this project stagnate like this and to see all those fixes wasted. I'm willing to check and document various fixes and write testing code if necessary. I'm not sure what you mean by a/b test cases but I'll figure it out. @aybe of you are willing to make me a collaborator let me know.

**Comment by TomQv** [comment]
Just ran into same. Was using Sensor-api for some years already with no problems with a x86-app, but now for a new app targeting x64 loads of random AccessViolationException. I have now knowledge of windows c++ api, so apart from just reporting I cant help any further.

```
 at Microsoft.WindowsAPICodePack.Shell.PropertySystem.PropVariantNativeMethods.PropVariantClear(PropVariant pvar)
at MS.WindowsAPICodePack.Internal.PropVariant.Finalize()

```
