### ISSUE TITLE
System.AccessViolationException in Microsoft.WindowsAPICodePack.dll with x64

### ISSUE THREAD

**Issue by TomQv** [aybe/Windows-API-Code-Pack-1.1#46]
Was using Sensor-api for some years already with no problems with a x86-app, but now for a new app targeting x64 loads of random AccessViolationException.

 at Microsoft.WindowsAPICodePack.Shell.PropertySystem.PropVariantNativeMethods.PropVariantClear(PropVariant pvar)
at MS.WindowsAPICodePack.Internal.PropVariant.Finalize()

I downloaded the developer-branch and added a try-catch in 
namespace .PropVariant.Dispose:

```
public void Dispose()
        {
            // Tom
            try
            {
                PropVariantNativeMethods.PropVariantClear(this);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("PropVariant.Dispose: " + ex.Message);
            }

            GC.SuppressFinalize(this);
        }
```

This seems to be a workaround, but what would be to correct fix? This routine is called very often, almost every second.

**Comment by TomQv** [comment]
Ok, looks like [this fix ](https://github.com/aybe/Windows-API-Code-Pack-1.1/pull/5/commits/fa2e6bfe443549580c2ec77d0c1b0d9cb551d9a3)solves the problem. So far no more exceptions, fine with x86 and x64.
Tom
