### ISSUE TITLE
 "The type initializer for 'Microsoft.WindowsAPICodePack.Shell.ShellObject' threw an exception." Occurs

### ISSUE THREAD

**Issue by KoujiHatta** [aybe/Windows-API-Code-Pack-1.1#56]
Use Microsoft.WindowsAPICodePack to display a folder selection dialog.
We are developing an application that specifies the file storage location.
， CommonOpenFileDialog class is used in the folder selection dialog.
 (version)
Microsoft.WindowsAPICodePack-Shell 1.1.0
Microsoft.WindowsAPICodePack-Core 1.1.0.2

Works fine in most environments, but folder selection in some environments
The following exception occurs when opening the dialog.
Exceptionally, the environment where the exception occurs is only known up to Win10 Pro.

```
The type initializer for 'Microsoft.WindowsAPICodePack.Shell.ShellObject' threw an exception.
   System.TypeInitializationException:The type initializer for 'Microsoft.WindowsAPICodePack.Shell.ShellObject' threw an exception.
   at Microsoft.WindowsAPICodePack.Shell.ShellObject.op_Inequality(ShellObject leftShellObject, ShellObject rightShellObject)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ApplyNativeSettings(IFileDialog dialog)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog()
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog(Window window)
   at xxxx()⇒ShowDialog in MyMethod
   System.InvalidOperationException:This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   at Microsoft.WindowsAPICodePack.Shell.ShellObject..cctor()
```
Below is the code

```csharp
    var folderDialog = new CommonOpenFileDialog("Test");
    folderDialog.IsFolderPicker = true;
    folderDialog.EnsureFileExists = true;
    if (Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) is string myDocumentsFolder)
    {
        folderDialog.InitialDirectory = myDocumentsFolder;
    }
    var result = folderDialog.ShowDialog(MyWindow);
    if (result == CommonFileDialogResult.Cancel)
    {
        Log("Cancel");
        return;
    }

```

What are the causes and countermeasures for this problem?
If a fix is ​​needed, it cannot be provided immediately, so there is a workaround that is effective in the problem environment.
Please tell me if there is.

**Comment by DanFTRX** [comment]
If your computer is set to follow FIPS compliance this will occur.  Its due to the use of the [MD5 Crypto Service in Shell Object](https://github.com/aybe/Windows-API-Code-Pack-1.1/blob/master/source/WindowsAPICodePack/Shell/Common/ShellObject.cs#L464).  Interestingly enough, the problem code isn't really even needed as its being used for the GetHashCode method which doesn't need cryptographic hashes.  You can try disabled fips in your application with a [flag in your app.config](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/enforcefipspolicy-element).  Or you can patch the offending code in a branch.  I don't think this repo is getting updated anymore though so good luck.

**Comment by johnthagen** [comment]
This has been fixed in the new active fork:

- [Microsoft-WindowsAPICodePack-6.0](https://github.com/samypr100/Windows-API-Code-Pack-1.1)
