### ISSUE TITLE
ExplorerBrowser Crashes Visual Studio when Exiting Debug

### ISSUE THREAD

**Issue by k5dmh** [aybe/Windows-API-Code-Pack-1.1#62]
I started an application which uses the ExplorerBrowser on a Windows form.  When exiting the application Visual Studio crashes.   I attempted to resolve this by disposing the control on form close.  I am not sure what else can be done to prevent the crash. 
 The event log will contain different errors but Visual Studio always crashes. 

Here are a couple of the errors:
-----------------------------
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 6EDFA44D (6ED30000) with exit code 80131506.

-----------------------------
Faulting application name: devenv.exe, version: 16.7.30523.141, time stamp: 0x5f6ba764
Faulting module name: ntdll.dll, version: 10.0.18362.1049, time stamp: 0x37fd3042
Exception code: 0xc0000374
Fault offset: 0x000dfa1d
Faulting process id: 0x193c
Faulting application start time: 0x01d69f4290fcd738
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 1e0e3290-8045-4a2f-92a9-7d9b607ccc54
Faulting package full name: 

-----------------------------
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Stack:
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalProbeForSatelliteAssemblyNextToParentAssembly(System.Reflection.AssemblyName, System.String, System.String, System.Globalization.CultureInfo, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(System.String, System.Globalization.CultureInfo, System.Version, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(System.Globalization.CultureInfo, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetObject(System.String, System.Globalization.CultureInfo, Boolean)
   at System.Resources.ResourceManager.GetObject(System.String)
   at Microsoft.VisualStudio.DesignTools.Diagnostics.Utility.ClrResourceManager.GetObject(System.String)
   at Microsoft.VisualStudio.DesignTools.Diagnostics.Utility.IconCache.GetTypeIcon(System.String, Microsoft.VisualStudio.DesignTools.Diagnostics.Utility.TypeIconSize)
   at Microsoft.VisualStudio.DesignTools.Diagnostics.Utility.IconCache..ctor(Microsoft.VisualStudio.DesignTools.Diagnostics.Utility.IResourceManager)
   at Microsoft.VisualStudio.DesignTools.Diagnostics.Utility.IconCache..ctor()
   at Microsoft.VisualStudio.DesignTools.Diagnostics.Model.XamlDiagnosticsHost..ctor(System.IServiceProvider, Microsoft.VisualStudio.DesignTools.Diagnostics.Telemetry.ITelemetryLogger, Microsoft.VisualStudio.DesignTools.Diagnostics.Utility.IErrorReporting, Microsoft.VisualStudio.DesignTools.Diagnostics.Bindings.IBindingFailuresProvider)
   at Microsoft.VisualStudio.DesignTools.Diagnostics.VisualStudioXamlDiagnosticsHost..ctor(System.IServiceProvider, Microsoft.VisualStudio.DesignTools.Diagnostics.Bindings.IBindingFailuresProvider)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at Microsoft.VisualStudio.Composition.ReflectionHelpers.Instantiate(System.Reflection.MethodBase, System.Object[])
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory+RuntimeExportProvider+RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider+PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider+PartLifecycleTracker.MoveNext(PartLifecycleState)
   at Microsoft.VisualStudio.Composition.ExportProvider+PartLifecycleTracker.MoveToState(PartLifecycleState)
   at Microsoft.VisualStudio.Composition.ExportProvider+PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider+<>c__DisplayClass55_0.<CreateExport>b__0()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   at Microsoft.VisualStudio.Composition.ExportProvider+<>c__DisplayClass71_1`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<GetExports>b__1()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at Microsoft.VisualStudio.DesignTools.Diagnostics.XamlDiagnosticsPackage.Initialize()
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(Microsoft.VisualStudio.OLE.Interop.IServiceProvider)

**Comment by k5dmh** [comment]
Created a new project using .Net 4.0 and the problem was resolved.  First project was .Net 4.6.1.
