### ISSUE TITLE
NullReferenceException when attempting to access ShellProperty inside PLINQ

### ISSUE THREAD

**Issue by SteveHarveyUK** [aybe/Windows-API-Code-Pack-1.1#8]
I have a class that uses the following code to pull some extended properties in its constructor:

            using (var shellObject = ShellObject.FromParsingName(path))
            {
                DateTaken = shellObject.Properties.GetProperty<DateTime?> SystemProperties.System.Photo.DateTaken).Value;
                Camera = new Camera(shellObject);
            }

I'm creating these objects with a PLINQ expression, if I use a WithDegreeOfParallelism 
value of greater than one - to push object creation across multple threads I get a NullReferenceException exception. (I've appended the call stack on the end.)

The same code runs fine if I use a WithDegreeOfParallelism value of 1 - meaning only one thread.

Top of Call Stack
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.WindowsAPICodePack.Shell.PropertySystem.ShellPropertyFactory.GenericCreateShellProperty[T](PropertyKey propKey, T thirdArg)
   at Microsoft.WindowsAPICodePack.Shell.PropertySystem.ShellPropertyFactory.CreateShellProperty(PropertyKey propKey, ShellObject shellObject)
   at Microsoft.WindowsAPICodePack.Shell.PropertySystem.ShellProperties.CreateTypedProperty(PropertyKey propKey)
   at Microsoft.WindowsAPICodePack.Shell.PropertySystem.ShellProperties.GetProperty[T](PropertyKey key)
   at PhotoSyncLib.Photo..ctor(String path) in d:\GitHub\PhotoSync\PhotoSyncLib\Photo.cs:line 33

**Comment by AzeExMachina** [comment]
Hi there, sorry for posting after such a long time, I am having this issue too, have you perhaps solved it?

**Comment by SteveHarveyUK** [comment]
Hi @AzeExMachina,
Blimey, I'd totally forgotten about this question. Unfortunately, I never found a solution.

**Comment by AzeExMachina** [comment]
Hi @SteveHarveyUK thanks for the answer. In the end I was able to find a solution, though it involved changing the source code by adding locks, since it was not thread safe
